{% set name = "conflowgen" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1519cd01162ad3ebedf46c71254aa6b7609aff4203fd1dc3bd26fecbebfa787e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pandas >=1
    - numpy
    - scipy
    - peewee >=3
    - enum_tools >=0.7
    - matplotlib-base
    - plotly
    - python-kaleido
    - seaborn
    - openpyxl

test:
  imports:
    - conflowgen
  requires:
    - pytest
    - pip
  source_files:
    - conflowgen/tests
  commands:
    - pytest conflowgen
    - pip check

about:
  home: https://github.com/1kastner/conflowgen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A generator for synthetic container flows at maritime container terminals with a focus on yard operations'
  doc_url: https://conflowgen.readthedocs.io/
  dev_url: https://github.com/1kastner/conflowgen

extra:
  recipe-maintainers:
    - 1kastner
